# Dependencies
highlighter:      rouge
gems: 		  [jekyll-paginate]
# Permalinks
permalink:        pretty

# Setup
title:            George's blog
tagline:          'random thoughts'
description:      'Thoughts about what I read and what I currently work with.'
url:              http://blog.georgebejan.com
baseurl:          /

author:
  name:           'George Bejan'
  url:            http://georgebejan.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
